import sqlite3
from db import get_connection

conn = get_connection()
conn.execute("PRAGMA foreign_keys = ON")
cursor = conn.cursor()

partes = [
        {
            "parte_numero":          "PO-2024-001",
            "fecha_parte":           "2024-01-10",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        1,
            "relevo_id":             2,
            "hora_inicio_relevo":    "14:00",
            "hora_fin_relevo":       "22:00",
            "pk_inicio_km":          0,
            "pk_inicio_m":           0,
            "pk_fin_km":             5,
            "pk_fin_m":              500,
            "tipo_terreno_id":       1,
            "seccion_tipo_id":       1,
            "total_actividades_min": 120,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         "Parte de prueba. Sin incidencias.",
            "estado_id":             1,
        },
        {
            "parte_numero":          "PO-2024-002",
            "fecha_parte":           "2024-01-15",
            "canal_codigo":          "APP",
            "canal_nombre":          "Aplicacion Movil",
            "responsable_id":        2,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          5,
            "pk_inicio_m":           500,
            "pk_fin_km":             12,
            "pk_fin_m":              0,
            "tipo_terreno_id":       2,
            "seccion_tipo_id":       2,
            "total_actividades_min": 240,
            "exceso_justificado":    1,
            "motivo_exceso_id":      1,
            "justificacion_exceso":  "Averia en maquinaria principal.",
            "hubo_averias":          1,
            "hubo_paradas":          0,
            "observaciones":         "Se produjo una averia que retraso los trabajos.",
            "estado_id":             3,
        },
        {
            "parte_numero":          "PO-2024-003",
            "fecha_parte":           "2024-02-03",
            "canal_codigo":          "TEL",
            "canal_nombre":          "Telefono",
            "responsable_id":        3,
            "relevo_id":             4,
            "hora_inicio_relevo":    "06:00",
            "hora_fin_relevo":       "14:00",
            "pk_inicio_km":          12,
            "pk_inicio_m":           0,
            "pk_fin_km":             18,
            "pk_fin_m":              750,
            "tipo_terreno_id":       3,
            "seccion_tipo_id":       3,
            "total_actividades_min": 180,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          1,
            "observaciones":         "Parada no prevista por paso de vehiculos especiales.",
            "estado_id":             1,
        },
        {
            "parte_numero":          "PO-2024-004",
            "fecha_parte":           "2024-02-20",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        4,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          0,
            "pk_inicio_m":           0,
            "pk_fin_km":             3,
            "pk_fin_m":              200,
            "tipo_terreno_id":       1,
            "seccion_tipo_id":       1,
            "total_actividades_min": 90,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         None,
            "estado_id":             2,
        },
        {
            "parte_numero":          "PO-2024-005",
            "fecha_parte":           "2024-03-05",
            "canal_codigo":          "APP",
            "canal_nombre":          "Aplicacion Movil",
            "responsable_id":        1,
            "relevo_id":             3,
            "hora_inicio_relevo":    "22:00",
            "hora_fin_relevo":       "23:59",
            "pk_inicio_km":          20,
            "pk_inicio_m":           0,
            "pk_fin_km":             28,
            "pk_fin_m":              300,
            "tipo_terreno_id":       2,
            "seccion_tipo_id":       2,
            "total_actividades_min": 300,
            "exceso_justificado":    1,
            "motivo_exceso_id":      2,
            "justificacion_exceso":  "Lluvia intensa que obligo a detener los trabajos.",
            "hubo_averias":          0,
            "hubo_paradas":          1,
            "observaciones":         "Condiciones meteorologicas adversas durante toda la jornada.",
            "estado_id":             3,
        },
        {
            "parte_numero":          "PO-2024-006",
            "fecha_parte":           "2024-03-18",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        2,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          1,
            "pk_inicio_m":           100,
            "pk_fin_km":             4,
            "pk_fin_m":              600,
            "tipo_terreno_id":       3,
            "seccion_tipo_id":       3,
            "total_actividades_min": 150,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         "Trabajos completados sin incidencias.",
            "estado_id":             2,
        },
        {
            "parte_numero":          "PO-2024-007",
            "fecha_parte":           "2024-04-02",
            "canal_codigo":          "TEL",
            "canal_nombre":          "Telefono",
            "responsable_id":        3,
            "relevo_id":             1,
            "hora_inicio_relevo":    "14:00",
            "hora_fin_relevo":       "20:00",
            "pk_inicio_km":          8,
            "pk_inicio_m":           0,
            "pk_fin_km":             15,
            "pk_fin_m":              0,
            "tipo_terreno_id":       1,
            "seccion_tipo_id":       1,
            "total_actividades_min": 210,
            "exceso_justificado":    1,
            "motivo_exceso_id":      3,
            "justificacion_exceso":  "Retenciones por accidente en via paralela.",
            "hubo_averias":          0,
            "hubo_paradas":          1,
            "observaciones":         "Trafico intenso afecto al acceso a la zona de trabajo.",
            "estado_id":             1,
        },
        {
            "parte_numero":          "PO-2024-008",
            "fecha_parte":           "2024-04-22",
            "canal_codigo":          "APP",
            "canal_nombre":          "Aplicacion Movil",
            "responsable_id":        4,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          0,
            "pk_inicio_m":           500,
            "pk_fin_km":             6,
            "pk_fin_m":              0,
            "tipo_terreno_id":       2,
            "seccion_tipo_id":       2,
            "total_actividades_min": 60,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          1,
            "hubo_paradas":          1,
            "observaciones":         "Averia en vehiculo y posterior parada para reparacion.",
            "estado_id":             3,
        },
        {
            "parte_numero":          "PO-2024-009",
            "fecha_parte":           "2024-05-10",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        1,
            "relevo_id":             4,
            "hora_inicio_relevo":    "08:00",
            "hora_fin_relevo":       "16:00",
            "pk_inicio_km":          10,
            "pk_inicio_m":           200,
            "pk_fin_km":             22,
            "pk_fin_m":              800,
            "tipo_terreno_id":       3,
            "seccion_tipo_id":       3,
            "total_actividades_min": 480,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         "Jornada completa sin incidencias destacables.",
            "estado_id":             2,
        },
        {
            "parte_numero":          "PO-2024-010",
            "fecha_parte":           "2024-05-28",
            "canal_codigo":          "TEL",
            "canal_nombre":          "Telefono",
            "responsable_id":        2,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          3,
            "pk_inicio_m":           0,
            "pk_fin_km":             9,
            "pk_fin_m":              500,
            "tipo_terreno_id":       1,
            "seccion_tipo_id":       2,
            "total_actividades_min": 135,
            "exceso_justificado":    1,
            "motivo_exceso_id":      1,
            "justificacion_exceso":  "Incidencia grave en via que requirio intervencion.",
            "hubo_averias":          1,
            "hubo_paradas":          0,
            "observaciones":         "Se coordino con servicios de emergencia.",
            "estado_id":             1,
        },
        {
            "parte_numero":          "PO-2024-011",
            "fecha_parte":           "2024-06-14",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        3,
            "relevo_id":             2,
            "hora_inicio_relevo":    "16:00",
            "hora_fin_relevo":       "22:00",
            "pk_inicio_km":          0,
            "pk_inicio_m":           0,
            "pk_fin_km":             2,
            "pk_fin_m":              100,
            "tipo_terreno_id":       2,
            "seccion_tipo_id":       1,
            "total_actividades_min": 75,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         None,
            "estado_id":             1,
        },
        {
            "parte_numero":          "PO-2024-012",
            "fecha_parte":           "2024-07-03",
            "canal_codigo":          "APP",
            "canal_nombre":          "Aplicacion Movil",
            "responsable_id":        4,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          15,
            "pk_inicio_m":           300,
            "pk_fin_km":             25,
            "pk_fin_m":              0,
            "tipo_terreno_id":       3,
            "seccion_tipo_id":       3,
            "total_actividades_min": 360,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         "Zona de dificil acceso pero sin incidencias.",
            "estado_id":             2,
        },
        {
            "parte_numero":          "PO-2024-013",
            "fecha_parte":           "2024-08-19",
            "canal_codigo":          "TEL",
            "canal_nombre":          "Telefono",
            "responsable_id":        1,
            "relevo_id":             3,
            "hora_inicio_relevo":    "12:00",
            "hora_fin_relevo":       "20:00",
            "pk_inicio_km":          7,
            "pk_inicio_m":           800,
            "pk_fin_km":             14,
            "pk_fin_m":              200,
            "tipo_terreno_id":       1,
            "seccion_tipo_id":       2,
            "total_actividades_min": 200,
            "exceso_justificado":    1,
            "motivo_exceso_id":      1,
            "justificacion_exceso":  "Fallo en equipo de medicion.",
            "hubo_averias":          1,
            "hubo_paradas":          1,
            "observaciones":         "Multiples incidencias durante la jornada.",
            "estado_id":             3,
        },
        {
            "parte_numero":          "PO-2024-014",
            "fecha_parte":           "2024-09-11",
            "canal_codigo":          "WEB",
            "canal_nombre":          "Canal Web",
            "responsable_id":        2,
            "relevo_id":             None,
            "hora_inicio_relevo":    None,
            "hora_fin_relevo":       None,
            "pk_inicio_km":          2,
            "pk_inicio_m":           0,
            "pk_fin_km":             8,
            "pk_fin_m":              400,
            "tipo_terreno_id":       2,
            "seccion_tipo_id":       1,
            "total_actividades_min": 110,
            "exceso_justificado":    0,
            "motivo_exceso_id":      None,
            "justificacion_exceso":  None,
            "hubo_averias":          0,
            "hubo_paradas":          0,
            "observaciones":         "Parte rutinario sin novedades.",
            "estado_id":             2,
        },
        {
            "parte_numero":          "PO-2024-015",
            "fecha_parte":           "2024-10-07",
            "canal_codigo":          "APP",
            "canal_nombre":          "Aplicacion Movil",
            "responsable_id":        4,
            "relevo_id":             2,
            "hora_inicio_relevo":    "06:00",
            "hora_fin_relevo":       "14:00",
            "pk_inicio_km":          30,
            "pk_inicio_m":           0,
            "pk_fin_km":             38,
            "pk_fin_m":              600,
            "tipo_terreno_id":       3,
            "seccion_tipo_id":       3,
            "total_actividades_min": 270,
            "exceso_justificado":    1,
            "motivo_exceso_id":      2,
            "justificacion_exceso":  "Niebla densa que dificulto los trabajos.",
            "hubo_averias":          0,
            "hubo_paradas":          1,
            "observaciones":         "Visibilidad reducida durante las primeras horas.",
            "estado_id":             1,
        },
    ]

if cursor.execute("SELECT COUNT(*) FROM ParteObra").fetchone()[0] == 0:
    cursor.executemany("""
        INSERT INTO ParteObra (
                        parte_numero, fecha_parte, canal_codigo, canal_nombre,
                        responsable_id, relevo_id, hora_inicio_relevo, hora_fin_relevo,
                        pk_inicio_km, pk_inicio_m, pk_fin_km, pk_fin_m,
                        tipo_terreno_id, seccion_tipo_id, total_actividades_min,
                        exceso_justificado, motivo_exceso_id, justificacion_exceso,
                        hubo_averias, hubo_paradas, observaciones, estado_id
                    ) VALUES (
                        :parte_numero, :fecha_parte, :canal_codigo, :canal_nombre,
                        :responsable_id, :relevo_id, :hora_inicio_relevo, :hora_fin_relevo,
                        :pk_inicio_km, :pk_inicio_m, :pk_fin_km, :pk_fin_m,
                        :tipo_terreno_id, :seccion_tipo_id, :total_actividades_min,
                        :exceso_justificado, :motivo_exceso_id, :justificacion_exceso,
                        :hubo_averias, :hubo_paradas, :observaciones, :estado_id
                    )
                """, partes)

conn.commit()
conn.close()
print("Partes de ejemplo insertados correctamente.")